# Generated by Django 6.0.3 on 2026-04-08 07:40

import commerce.models
import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('contact', models.CharField(blank=True, max_length=255, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
                ('role', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='commerce.role')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(help_text='Họ và tên đầy đủ', max_length=150)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(blank=True, help_text='Số điện thoại', max_length=20, null=True)),
                ('address', models.TextField(blank=True, help_text='Địa chỉ liên hệ', null=True)),
                ('position', models.CharField(help_text='Chức vụ trong công ty (VD: Quản lý, Nhân viên bán hàng)', max_length=100)),
                ('salary', models.DecimalField(blank=True, decimal_places=2, help_text='Mức lương', max_digits=10, null=True)),
                ('date_joined', models.DateField(default=django.utils.timezone.now, help_text='Ngày bắt đầu làm việc')),
                ('is_active', models.BooleanField(default=True, help_text='Trạng thái hoạt động của nhân viên')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='employee_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now, help_text='Ngày chấm công')),
                ('check_in', models.TimeField(blank=True, help_text='Giờ vào', null=True)),
                ('check_out', models.TimeField(blank=True, help_text='Giờ ra', null=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='commerce.employee')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('pending', 'Đang xử lý'), ('paid', 'Đã thanh toán'), ('shipped', 'Đã giao hàng'), ('completed', 'Hoàn thành'), ('cancelled', 'Đã hủy')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('image', models.ImageField(blank=True, null=True, upload_to=commerce.models.product_image_upload_path)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='commerce.category')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='commerce.supplier')),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('note', models.TextField(blank=True, null=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='commerce.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='commerce.product')),
            ],
        ),
        migrations.CreateModel(
            name='FlashSale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discount_percent', models.PositiveIntegerField(help_text='Phần trăm giảm giá, ví dụ 20 cho 20% giảm giá')),
                ('sale_price', models.DecimalField(decimal_places=2, help_text='Giá bán trong flash sale (tính tự động từ % giảm)', max_digits=10)),
                ('start_date', models.DateField(default=django.utils.timezone.now)),
                ('end_date', models.DateField()),
                ('active', models.BooleanField(default=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flash_sales', to='commerce.product')),
            ],
        ),
        migrations.CreateModel(
            name='ProductComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(help_text='Nội dung bình luận của khách hàng')),
                ('rating', models.PositiveSmallIntegerField(blank=True, help_text='Đánh giá sản phẩm (từ 1 đến 5)', null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='commerce.product')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProductDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(blank=True, help_text='Thương hiệu sản phẩm', max_length=100, null=True)),
                ('manufacturer', models.CharField(blank=True, help_text='Nhà sản xuất', max_length=100, null=True)),
                ('country_of_origin', models.CharField(blank=True, help_text='Xuất xứ (quốc gia)', max_length=100, null=True)),
                ('weight', models.DecimalField(blank=True, decimal_places=2, help_text='Trọng lượng (gam hoặc kg)', max_digits=6, null=True)),
                ('volume', models.DecimalField(blank=True, decimal_places=2, help_text='Thể tích (ml hoặc l)', max_digits=6, null=True)),
                ('packaging_type', models.CharField(blank=True, help_text='Loại bao bì, ví dụ: hộp, chai, túi', max_length=100, null=True)),
                ('ingredients', models.TextField(blank=True, help_text='Danh sách thành phần', null=True)),
                ('nutrition_facts', models.TextField(blank=True, help_text='Thông tin dinh dưỡng (ví dụ: trên 100g hoặc mỗi khẩu phần)', null=True)),
                ('allergens', models.CharField(blank=True, help_text='Cảnh báo dị ứng nếu có', max_length=255, null=True)),
                ('manufacturing_date', models.DateField(blank=True, help_text='Ngày sản xuất', null=True)),
                ('expiration_date', models.DateField(blank=True, help_text='Hạn sử dụng', null=True)),
                ('storage_instructions', models.TextField(blank=True, help_text='Hướng dẫn bảo quản', null=True)),
                ('usage_instructions', models.TextField(blank=True, help_text='Hướng dẫn sử dụng nếu cần', null=True)),
                ('additional_info', models.TextField(blank=True, help_text='Thông tin bổ sung khác', null=True)),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='food_detail', to='commerce.product')),
            ],
        ),
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='promotions/')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('active', models.BooleanField(default=True)),
                ('products', models.ManyToManyField(blank=True, to='commerce.product')),
            ],
        ),
        migrations.CreateModel(
            name='WorkSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(help_text='Ngày làm việc')),
                ('shift_type', models.CharField(choices=[('morning', 'Sáng'), ('afternoon', 'Chiều'), ('night', 'Tối'), ('custom', 'Tùy chỉnh')], default='morning', help_text='Loại ca làm việc', max_length=20)),
                ('start_time', models.TimeField(help_text='Giờ bắt đầu ca')),
                ('end_time', models.TimeField(help_text='Giờ kết thúc ca')),
                ('is_swapped', models.BooleanField(default=False, help_text='Đánh dấu ca đã được thay đổi hay chưa')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_schedules', to='commerce.employee')),
                ('swapped_with', models.ForeignKey(blank=True, help_text='Ca làm việc được thay đổi (nếu có)', null=True, on_delete=django.db.models.deletion.SET_NULL, to='commerce.workschedule')),
            ],
            options={
                'ordering': ['date', 'start_time'],
                'unique_together': {('employee', 'date', 'shift_type')},
            },
        ),
        migrations.CreateModel(
            name='ShiftSwapRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requested_at', models.DateTimeField(auto_now_add=True, help_text='Thời gian gửi yêu cầu')),
                ('status', models.CharField(choices=[('pending', 'Chờ xử lý'), ('approved', 'Đã duyệt'), ('rejected', 'Bị từ chối')], default='pending', help_text='Trạng thái yêu cầu', max_length=20)),
                ('note', models.TextField(blank=True, help_text='Ghi chú hoặc lý do thay ca', null=True)),
                ('schedule_from', models.ForeignKey(help_text='Ca làm việc của người gửi yêu cầu', on_delete=django.db.models.deletion.CASCADE, related_name='swap_requests_sent', to='commerce.workschedule')),
                ('schedule_to', models.ForeignKey(help_text='Ca làm việc của người nhận yêu cầu', on_delete=django.db.models.deletion.CASCADE, related_name='swap_requests_received', to='commerce.workschedule')),
            ],
        ),
    ]
