# Generated by Django 4.2.20 on 2025-03-23 04:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0006_promotion_products_alter_promotion_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='promotion',
            options={'verbose_name': 'Khuyến mãi', 'verbose_name_plural': 'Các khuyến mãi'},
        ),
    ]
