# Generated by Django 4.2.20 on 2025-03-27 08:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0008_alter_promotion_options_flashsale'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flashsale',
            name='sale_price',
            field=models.DecimalField(decimal_places=2, help_text='Giá bán trong flash sale (tính tự động từ % giảm)', max_digits=10),
        ),
        migrations.CreateModel(
            name='FoodProductDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(blank=True, help_text='Thương hiệu sản phẩm', max_length=100, null=True)),
                ('manufacturer', models.CharField(blank=True, help_text='Nhà sản xuất', max_length=100, null=True)),
                ('country_of_origin', models.CharField(blank=True, help_text='Xuất xứ (quốc gia)', max_length=100, null=True)),
                ('weight', models.DecimalField(blank=True, decimal_places=2, help_text='Trọng lượng (gam hoặc kg)', max_digits=6, null=True)),
                ('volume', models.DecimalField(blank=True, decimal_places=2, help_text='Thể tích (ml hoặc l)', max_digits=6, null=True)),
                ('packaging_type', models.CharField(blank=True, help_text='Loại bao bì, ví dụ: hộp, chai, túi', max_length=100, null=True)),
                ('ingredients', models.TextField(blank=True, help_text='Danh sách thành phần', null=True)),
                ('nutrition_facts', models.TextField(blank=True, help_text='Thông tin dinh dưỡng (ví dụ: trên 100g hoặc mỗi khẩu phần)', null=True)),
                ('allergens', models.CharField(blank=True, help_text='Cảnh báo dị ứng nếu có', max_length=255, null=True)),
                ('manufacturing_date', models.DateField(blank=True, help_text='Ngày sản xuất', null=True)),
                ('expiration_date', models.DateField(blank=True, help_text='Hạn sử dụng', null=True)),
                ('storage_instructions', models.TextField(blank=True, help_text='Hướng dẫn bảo quản', null=True)),
                ('usage_instructions', models.TextField(blank=True, help_text='Hướng dẫn sử dụng nếu cần', null=True)),
                ('additional_info', models.TextField(blank=True, help_text='Thông tin bổ sung khác', null=True)),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='food_detail', to='commerce.product')),
            ],
        ),
    ]
