# Generated by Django 4.2.20 on 2025-03-27 08:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0009_alter_flashsale_sale_price_foodproductdetail'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FoodProductDetail',
            new_name='ProductDetail',
        ),
    ]
