# Generated by Django 4.2.20 on 2025-03-29 03:06

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0012_alter_productcomment_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(help_text='Họ và tên đầy đủ', max_length=150)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(blank=True, help_text='Số điện thoại', max_length=20, null=True)),
                ('address', models.TextField(blank=True, help_text='Địa chỉ liên hệ', null=True)),
                ('position', models.CharField(help_text='Chức vụ trong công ty (VD: Quản lý, Nhân viên bán hàng)', max_length=100)),
                ('salary', models.DecimalField(blank=True, decimal_places=2, help_text='Mức lương', max_digits=10, null=True)),
                ('date_joined', models.DateField(default=django.utils.timezone.now, help_text='Ngày bắt đầu làm việc')),
                ('is_active', models.BooleanField(default=True, help_text='Trạng thái hoạt động của nhân viên')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='employee_profile', to='commerce.user')),
            ],
        ),
    ]
