# Generated by Django 4.2.20 on 2025-03-29 03:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0013_employee'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(help_text='Ngày làm việc')),
                ('shift_type', models.CharField(choices=[('morning', 'Sáng'), ('afternoon', 'Chiều'), ('night', 'Tối'), ('custom', 'Tùy chỉnh')], default='morning', help_text='Loại ca làm việc', max_length=20)),
                ('start_time', models.TimeField(help_text='Giờ bắt đầu ca')),
                ('end_time', models.TimeField(help_text='Giờ kết thúc ca')),
                ('is_swapped', models.BooleanField(default=False, help_text='Đánh dấu ca đã được thay đổi hay chưa')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_schedules', to='commerce.employee')),
                ('swapped_with', models.ForeignKey(blank=True, help_text='Ca làm việc được thay đổi (nếu có)', null=True, on_delete=django.db.models.deletion.SET_NULL, to='commerce.workschedule')),
            ],
            options={
                'ordering': ['date', 'start_time'],
                'unique_together': {('employee', 'date', 'shift_type')},
            },
        ),
        migrations.CreateModel(
            name='ShiftSwapRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requested_at', models.DateTimeField(auto_now_add=True, help_text='Thời gian gửi yêu cầu')),
                ('status', models.CharField(choices=[('pending', 'Chờ xử lý'), ('approved', 'Đã duyệt'), ('rejected', 'Bị từ chối')], default='pending', help_text='Trạng thái yêu cầu', max_length=20)),
                ('note', models.TextField(blank=True, help_text='Ghi chú hoặc lý do thay ca', null=True)),
                ('schedule_from', models.ForeignKey(help_text='Ca làm việc của người gửi yêu cầu', on_delete=django.db.models.deletion.CASCADE, related_name='swap_requests_sent', to='commerce.workschedule')),
                ('schedule_to', models.ForeignKey(help_text='Ca làm việc của người nhận yêu cầu', on_delete=django.db.models.deletion.CASCADE, related_name='swap_requests_received', to='commerce.workschedule')),
            ],
        ),
    ]
