# Generated by Django 4.2.20 on 2025-03-29 04:14

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0014_workschedule_shiftswaprequest'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now, help_text='Ngày chấm công')),
                ('check_in', models.TimeField(blank=True, help_text='Giờ vào', null=True)),
                ('check_out', models.TimeField(blank=True, help_text='Giờ ra', null=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='commerce.employee')),
            ],
        ),
    ]
